// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Color
    {
        public Color()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int id_Color { get; set; }
        public string ColorName { get; set; }
        public string ColorPic { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}