// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class ConsigmentNote
    {
        public int id_Order { get; set; }
        public int id_Product { get; set; }
        public decimal? Count { get; set; }

        public virtual Product id_Order1 { get; set; }
        public virtual Order id_OrderNavigation { get; set; }
    }
}