// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Engine
    {
        public Engine()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int id_Engine { get; set; }
        public string EngineName { get; set; }
        public int? Power { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}