// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Mark
    {
        public Mark()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int id_Mark { get; set; }
        public string MarkName { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}