// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class PaymentType
    {
        public PaymentType()
        {
            Orders = new HashSet<Order>();
        }

        public int id_PaymentType { get; set; }
        public string PaymentTypeName { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}