// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Person
    {
        public Person()
        {
            Orderid_PersonNavigations = new HashSet<Order>();
            Orderid_SellerNavigations = new HashSet<Order>();
            SrviceLists = new HashSet<SrviceList>();
            Vehicles = new HashSet<Vehicle>();
        }

        public int id_Person { get; set; }
        public int id_Gender { get; set; }
        public int id_Role { get; set; }
        public string FirstName { get; set; }
        public string SureName { get; set; }
        public string Patronimic { get; set; }
        public DateTime? BDay { get; set; }
        public string EMail { get; set; }
        public string PhoneNumber { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }

        public virtual Gender id_GenderNavigation { get; set; }
        public virtual Role id_RoleNavigation { get; set; }
        public virtual ICollection<Order> Orderid_PersonNavigations { get; set; }
        public virtual ICollection<Order> Orderid_SellerNavigations { get; set; }
        public virtual ICollection<SrviceList> SrviceLists { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}