// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Product
    {
        public Product()
        {
            ConsigmentNotes = new HashSet<ConsigmentNote>();
        }

        public int id_Product { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductDiscription { get; set; }
        public string ProductPicture { get; set; }
        public int Status { get; set; }

        public virtual ICollection<ConsigmentNote> ConsigmentNotes { get; set; }
    }
}