// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Role
    {
        public Role()
        {
            People = new HashSet<Person>();
        }

        public int id_Role { get; set; }
        public string RoleName { get; set; }

        public virtual ICollection<Person> People { get; set; }
    }
}