// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Service
    {
        public Service()
        {
            SrviceLists = new HashSet<SrviceList>();
        }

        public int id_Service { get; set; }
        public string ServiceName { get; set; }
        public decimal? ServicePrice { get; set; }

        public virtual ICollection<SrviceList> SrviceLists { get; set; }
    }
}