// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class SrviceList
    {
        public int id_Order { get; set; }
        public int id_Services { get; set; }
        public int id_Person { get; set; }

        public virtual Order id_OrderNavigation { get; set; }
        public virtual Person id_PersonNavigation { get; set; }
        public virtual Service id_ServicesNavigation { get; set; }
    }
}