// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1
{
    public partial class Transmission
    {
        public Transmission()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int id_Transmission { get; set; }
        public string TransmissionName { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}