// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class Order
{
    public int id_Order { get; set; }

    public int id_Person { get; set; }

    public int id_Vichicle { get; set; }

    public int id_Seller { get; set; }

    public int id_PaymentType { get; set; }

    public int id_OrderStatus { get; set; }

    public DateTime? RegDate { get; set; }

    public TimeSpan? RegTime { get; set; }

    public DateTime? ComplDate { get; set; }

    public TimeSpan? ComplTime { get; set; }

    public int OrderNumber { get; set; }

    public virtual ICollection<ConsigmentNote> ConsigmentNotes { get; set; } = new List<ConsigmentNote>();

    public virtual ICollection<SrviceList> SrviceLists { get; set; } = new List<SrviceList>();

    public virtual OrederStatus id_OrderStatusNavigation { get; set; }

    public virtual PaymentType id_PaymentTypeNavigation { get; set; }

    public virtual Person id_PersonNavigation { get; set; }

    public virtual Person id_SellerNavigation { get; set; }
}