// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class PaymentType
{
    public int id_PaymentType { get; set; }

    public string PaymentTypeName { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}